config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :track_events

  root to: 'track_events#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/track_event.rb
class TrackEvent < ApplicationRecord
  belongs_to :user

  scope :in_range, -> range {
    where('(time_in BETWEEN ? AND ?) OR (time_out BETWEEN ? AND ?)', range.first, range.last, range.first, range.last)
  }
  scope :exclude_self, -> id { where.not(id: id) }

  validates_presence_of :time_in, message: 'Log should be present first!', on: :create, if: -> { self.user }
  validate :last_event_completed, on: :create
  validate :valid_times
  validate :cannot_overlap_another_event, if: -> { self.user }

  def last_event_completed
    errors.add(:punch_out, 'or Update Out Time to complete previous TimeLog first!') if self.user && !self.user.last_event_completed?
  end

  def valid_times
    if time_in && time_out && time_in > time_out
      self.errors.add :time_in, ' has to be before time out'
    end
  end

  def cannot_overlap_another_event
    return unless errors.blank?
    in_time = self.time_in || Time.now - 100.years
    out_time = self.time_out || Time.now + 100.years
    range = Range.new in_time, out_time 

    overlaps = self.user.track_events.exclude_self(id).in_range(range)
    overlap_error unless overlaps.empty?
  end

  def overlap_error
    errors.add(:overlap_error, 'There is already a TimeLog prevent in this hour!')
  end

  def complete?
    !self.time_out.blank?
  end

  def assign_time_in
    self.time_in = Time.now
  end

  def assign_time_out
    self.time_out = Time.now
  end

  def assign_time(val='Punch In!')
    if val == 'Punch Out!'
      if self.user && !self.user.last_event_completed?
        event = self.user.last_event
        event.assign_time_out
        return event
      end
    else
      self.assign_time_in
    end
    return self
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true, uniqueness: true

  has_many :track_events, -> { order(time_in: :desc) }

  def last_event_completed?
    self.track_events.blank? || self.track_events.first.complete?
  end

  def last_event
    self.track_events.first
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/track_events_controller.rb
class TrackEventsController < ApplicationController
  before_action :authenticate_user!, except: [:new, :create, :show]
  before_action :set_track_event, only: [:show, :edit, :update, :destroy]
  before_action :set_event_user, only: [:create]

  # GET /track_events
  # GET /track_events.json
  def index
    @track_events = current_user.track_events
  end

  # GET /track_events/1
  # GET /track_events/1.json
  def show
  end

  # GET /track_events/new
  def new
    @track_event = TrackEvent.new
  end

  # GET /track_events/1/edit
  def edit
  end

  # POST /track_events
  # POST /track_events.json
  def create
    @track_event = TrackEvent.new(track_event_params)
    @track_event = @track_event.assign_time(params[:commit]) if !current_user && @event_user

    respond_to do |format|
      if @track_event.save
        if current_user
          format.html { redirect_to @track_event, notice: 'Track event was successfully created.' }
          format.json { render :show, status: :created, location: @track_event }
        else
          format.html { redirect_to new_track_event_path, notice: 'Track event was successfully created.' }
          format.json { render :show, status: :created, location: @track_event }
        end
      else
        format.html { render :new }
        format.json { render json: @track_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /track_events/1
  # PATCH/PUT /track_events/1.json
  def update
    respond_to do |format|
      if @track_event.update(track_event_params)
        format.html { redirect_to @track_event, notice: 'Track event was successfully updated.' }
        format.json { render :show, status: :ok, location: @track_event }
      else
        format.html { render :edit }
        format.json { render json: @track_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /track_events/1
  # DELETE /track_events/1.json
  def destroy
    @track_event.destroy
    respond_to do |format|
      format.html { redirect_to track_events_url, notice: 'Track event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_track_event
      @track_event = TrackEvent.find(params[:id])
    end

    def set_event_user
      @event_user = current_user || User.find_by(name: params[:track_event][:your_name])
      params[:track_event][:user_id] = @event_user.id if @event_user
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def track_event_params
      params.fetch(:track_event, {}).permit(:description, :time_in, :time_out, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/track_events_helper.rb
module TrackEventsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ClockEvent</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <%= render 'shared/navbar' %>
    </header>
    <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-md navbar-light bg-light">
	<a href="#" class="navbar-brand">Logo</a>
	<button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
	    <span class="navbar-toggler-icon"></span>
	</button>

	<div class="collapse navbar-collapse" id="navbarCollapse">
		<div class="navbar-nav">
	        <a href="#" class="nav-item nav-link active">Home</a>
	    </div>
	    <div class="navbar-nav ml-auto">
	        <% if user_signed_in? %>
		        <%= link_to current_user.email, edit_user_registration_path, class: "nav-item nav-link" %>
		        <%= link_to "Logout", destroy_user_session_path, class: "nav-item nav-link", method: :delete %>
		    <% else %>
		        <%= link_to "Sign Up", new_user_registration_path, class: "nav-item nav-link" %>
		        <%= link_to "Login", new_user_session_path, class: "nav-item nav-link" %>
		    <% end %>
	    </div>
	</div>
</nav>

app/views/track_events/_form.html.erb
<%= form_with(model: track_event, local: true) do |form| %>
  <% if track_event.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <h2><%= pluralize(track_event.errors.count, "error") %> prohibited this TimeLog from being saved:</h2>

      <ul>
        <% track_event.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <% if current_user || !track_event.new_record? %>
    <div class="form-group">
      <%= form.label :time_in, class: "col-sm-2 control-label" %>
      <div class="col-sm-6">
        <%= form.datetime_select :time_in, class: "form-control" %>
      </div>
    </div>

    <div class="form-group">
      <%= form.label :time_out, class: "col-sm-2 control-label" %>
      <div class="col-sm-6">
        <%= form.datetime_select :time_out, class: "form-control", include_blank: true %>
      </div>
    </div>

    <div class="form-group">
      <%= form.label :description, class: "col-sm-2 control-label" %>
      <div class="col-sm-6">
        <%= form.text_field :description, class: "form-control" %>
      </div>
    </div>

    <div class="col-sm-6">
      <%= form.submit 'Save TimeLog!', class: "btn btn-lg btn-primary" %>
    </div>
  <% else %>
    <div class="form-group">
      <%= form.label :your_name, class: "col-sm-2 control-label" %>
      <div class="col-sm-6">
        <%= form.text_field :your_name, class: "form-control" %>
      </div>
    </div>

    <div class="col-sm-6">
      <%= form.submit 'Punch In!', value: 'Punch In!', class: "btn btn-lg btn-primary" %>
      <%= form.submit 'Punch Out!', value: 'Punch Out!', class: "btn btn-lg btn-primary" %>
    </div>
  <% end %>

<% end %>

app/views/track_events/edit.html.erb
<div class="container">
  <div class="home-inner">
    <div class="wrapper">
		<h1>Editing TimeLog</h1>

		<%= render 'form', track_event: @track_event %>

		<%= link_to 'Show', @track_event %> |
		<%= link_to 'Back', track_events_path %>
	</div>
  </div>
</div>

app/views/track_events/index.html.erb
<div class="container">
  <div class="home-inner">
    <div class="wrapper">
<p id="notice" class="alert alert-success"><%= notice %></p>

<h1>TimeLogs</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Time In</th>
      <th>Time Out</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @track_events.each do |track_event| %>
      <tr>
        <td><%= track_event.time_in %></td>
        <td><%= track_event.time_out %></td>
        <td><%= track_event.description %></td>
        <td><%= link_to 'Show', track_event %></td>
        <td><%= link_to 'Edit', edit_track_event_path(track_event) %></td>
        <td><%= link_to 'Destroy', track_event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Track Event', new_track_event_path %>
</div>
</div>
</div>

app/views/track_events/new.html.erb
<div class="container">
  <div class="home-inner">
    <div class="wrapper">
    	<p id="notice" class="alert alert-success"><%= notice %></p>

    	<h1>TimeLog</h1>

		<%= render 'form', track_event: @track_event %>

		<%= link_to 'Back', track_events_path %>
	</div>
  </div>
</div>

app/views/track_events/show.html.erb
<div class="container">
  <div class="home-inner">
    <div class="wrapper">
    	<p id="notice" class="alert alert-success"><%= notice %></p>

		<%= link_to 'Edit', edit_track_event_path(@track_event) %> |
		<%= link_to 'Back', track_events_path %>
	</div>
  </div>
</div>